version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: focus-tracker-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
